Repository FusionAuth/fusionauth-javascript-sdk, pull requests merged in 2024-05, with the labels that each got.

#80 73 Remove Unused query-string Dependency from Vue SDK
  packages/sdk-vue/package.json
Labels: general issue

#81 Angular sdk v1.0
  packages/sdk-angular/CHANGES.md
  packages/sdk-angular/README.md
  packages/sdk-angular/docs/.nojekyll
  packages/sdk-angular/docs/README.md
  packages/sdk-angular/docs/classes/FusionAuthLoginButtonComponent.md
  packages/sdk-angular/docs/classes/FusionAuthLogoutButtonComponent.md
  packages/sdk-angular/docs/classes/FusionAuthModule.md
  packages/sdk-angular/docs/classes/FusionAuthRegisterButtonComponent.md
  packages/sdk-angular/docs/classes/FusionAuthService.md
  packages/sdk-angular/docs/interfaces/FusionAuthConfig.md
  packages/sdk-angular/docs/interfaces/UserInfo.md
  packages/sdk-angular/docs/modules.md
  packages/sdk-angular/package.json
  packages/sdk-angular/projects/fusionauth-angular-sdk/ng-package.json
  packages/sdk-angular/projects/fusionauth-angular-sdk/package.json
  packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/core.ts
  packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.spec.ts
  packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.ts
  packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/types.ts
  packages/sdk-angular/projects/fusionauth-angular-sdk/tsconfig.lib.json
  packages/sdk-angular/tsconfig.json
Labels: Angular

#83 Update root README to more accurately describe the SDK suite
  README.md
Labels: documentation

#87 Angular 1.0.1 CHANGES.md (change 1.0.0 --> 1.0.1)
  packages/sdk-angular/CHANGES.md
Labels: documentation, Angular

#88 React v2.1.1
  package.json
  packages/core/src/CookieHelpers/CookieHelpers.test.ts
  packages/core/src/CookieHelpers/CookieHelpers.ts
  packages/core/src/SDKConfig/SDKConfig.ts
  packages/core/src/SDKCore/SDKCore.test.ts
  packages/core/src/SDKCore/SDKCore.ts
  packages/core/src/TokenExpirationScheduler/TokenExpirationScheduler.ts
  packages/core/src/TokenExpirationScheduler/index.ts
  packages/core/src/TokenRefresher/TokenRefresher.test.ts
  packages/core/src/TokenRefresher/TokenRefresher.ts
  packages/core/src/TokenRefresher/index.ts
  packages/core/src/index.ts
  packages/sdk-react/CHANGES.md
  packages/sdk-react/docs/interfaces/FusionAuthProviderConfig.FusionAuthProviderConfig.md
  packages/sdk-react/docs/interfaces/FusionAuthProviderContext.FusionAuthProviderContext.md
  packages/sdk-react/docs/modules/FusionAuthProvider.md
  packages/sdk-react/package.json
  packages/sdk-react/src/components/providers/Context.tsx
  packages/sdk-react/src/components/providers/FusionAuthProvider.test.tsx
  packages/sdk-react/src/components/providers/FusionAuthProvider.tsx
  packages/sdk-react/src/components/providers/FusionAuthProviderConfig.ts
  packages/sdk-react/src/components/providers/FusionAuthProviderContext.ts
  packages/sdk-vue/src/createFusionAuth/createFusionAuth.test.ts
Labels: bug, enhancement, React, SDK Core

#89 Vue v1.0.1
  package.json
  packages/sdk-vue/CHANGES.md
  packages/sdk-vue/docs/README.md
  packages/sdk-vue/docs/interfaces/types.FusionAuth.md
  packages/sdk-vue/docs/interfaces/types.FusionAuthConfig.md
  packages/sdk-vue/docs/interfaces/types.UserInfo.md
  packages/sdk-vue/docs/modules/composables_useFusionAuth.md
  packages/sdk-vue/package.json
  packages/sdk-vue/src/createFusionAuth/createFusionAuth.test.ts
  packages/sdk-vue/src/types.ts
  packages/sdk-vue/web-types.json
Labels: bug, enhancement, Vue

#90 Angular v1.0.2
  packages/sdk-angular/CHANGES.md
  packages/sdk-angular/docs/classes/FusionAuthLoginButtonComponent.md
  packages/sdk-angular/docs/classes/FusionAuthLogoutButtonComponent.md
  packages/sdk-angular/docs/classes/FusionAuthModule.md
  packages/sdk-angular/docs/classes/FusionAuthRegisterButtonComponent.md
  packages/sdk-angular/docs/classes/FusionAuthService.md
  packages/sdk-angular/docs/interfaces/FusionAuthConfig.md
  packages/sdk-angular/docs/interfaces/UserInfo.md
  packages/sdk-angular/projects/fusionauth-angular-sdk/package.json
  packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/core.ts
  packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.spec.ts
  packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.ts
  packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/types.ts
Labels: bug, enhancement, Angular

#91 Fix indentation for Table of Contents on vue README
  packages/sdk-vue/README.md
Labels: documentation

#96 Add onboarding notes to root README
  README.md
Labels: documentation

#98 Vue SDK v1.1.0
  package.json
  packages/core/src/CookieHelpers/CookieHelpers.test.ts
  packages/core/src/CookieHelpers/CookieHelpers.ts
  packages/core/src/RedirectHelper/RedirectHelper.ts
  packages/core/src/SDKConfig/SDKConfig.ts
  packages/core/src/SDKCore/SDKCore.ts
  packages/core/src/index.ts
  packages/sdk-vue/CHANGES.md
  packages/sdk-vue/README.md
  packages/sdk-vue/docs/README.md
  packages/sdk-vue/docs/interfaces/types.FusionAuth.md
  packages/sdk-vue/docs/interfaces/types.FusionAuthConfig.md
  packages/sdk-vue/docs/interfaces/types.UserInfo.md
  packages/sdk-vue/docs/modules/composables_useFusionAuth.md
  packages/sdk-vue/package.json
  packages/sdk-vue/src/createFusionAuth/NuxtUseCookieAdapter.ts
  packages/sdk-vue/src/createFusionAuth/createFusionAuth.ts
  packages/sdk-vue/src/types.ts
Labels: Vue

#100 Add ReactSDK SSR to known issues in README
  packages/sdk-react/README.md
Labels: documentation, React

#101 Fix typo in root README
  README.md
Labels: documentation

#102 Add React and Vue sourcemaps for debugging
  packages/core/tsconfig.json
  packages/core/vite.config.ts
  packages/sdk-react/CHANGES.md
  packages/sdk-react/tsconfig.json
  packages/sdk-react/vite.config.ts
  packages/sdk-vue/CHANGES.md
  packages/sdk-vue/docs/README.md
  packages/sdk-vue/docs/interfaces/types.FusionAuth.md
  packages/sdk-vue/docs/interfaces/types.FusionAuthConfig.md
  packages/sdk-vue/docs/interfaces/types.UserInfo.md
  packages/sdk-vue/docs/modules/composables_useFusionAuth.md
  packages/sdk-vue/tsconfig.json
  packages/sdk-vue/vite.config.ts
  packages/sdk-vue/web-types.json
Labels: general issue

#103 46 Add postLogoutRedirectUri Param Handling
  packages/core/src/SDKCore/SDKCore.ts
  packages/core/src/UrlHelper/UrlHelper.test.ts
  packages/core/src/UrlHelper/UrlHelper.ts
  packages/core/src/UrlHelper/UrlHelperTypes.ts
  packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/core.ts
  packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/types.ts
  packages/sdk-react/src/components/providers/FusionAuthProviderConfig.ts
  packages/sdk-react/src/testing-tools/mocks/testConfig.ts
  packages/sdk-vue/src/types.ts
Labels: enhancement

#106 Add '>=' to peer dependencies for all packages
  packages/sdk-angular/projects/fusionauth-angular-sdk/package.json
  packages/sdk-react/package.json
  packages/sdk-vue/package.json
Labels: general issue
